version = 0.1
[default.pipeline_bootstrap.parameters]
oidc_provider_url = "https://token.actions.githubusercontent.com"
oidc_client_id = "sts.amazonaws.com"
github_org = "dapulid-git"
github_repo = "api-serverless"
deployment_branch = "main"
oidc_provider = "github-actions"
permissions_provider = "OpenID Connect (OIDC)"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::471112892305:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-SjpEpHaiLNIa"
cloudformation_execution_role = "arn:aws:iam::471112892305:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-ycudM1IrlGZi"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-ahdvvglagzam"
image_repository = ""
region = "us-east-1"
